spring.application.name=SB-HotelManagement-Assessment

server.port=9092
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=capgdb
spring.datasource.password=capgdb

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
